Repository openfrontio/OpenFrontIO, pull requests merged in 2025-06, with the labels that each got.

#992 Equalize team sizes
  src/core/configuration/Config.ts
  src/core/configuration/DefaultConfig.ts
  src/server/MapPlaylist.ts
Labels: Balance Tweak

#1000 Use bigint for gold
  src/client/Transport.ts
  src/client/Utils.ts
  src/client/graphics/layers/BuildMenu.ts
  src/client/graphics/layers/ChatModal.ts
  src/client/graphics/layers/ControlPanel.ts
  src/client/graphics/layers/EventsDisplay.ts
  src/client/graphics/layers/PlayerPanel.ts
  src/client/graphics/layers/TeamStats.ts
  src/client/graphics/layers/TopBar.ts
  src/core/Schemas.ts
  src/core/configuration/Config.ts
  src/core/configuration/DefaultConfig.ts
  src/core/execution/ConstructionExecution.ts
  src/core/execution/DonateGoldExecution.ts
  src/core/execution/DonateTroopExecution.ts
  src/core/execution/FakeHumanExecution.ts
  src/core/game/Game.ts
  src/core/game/GameUpdates.ts
  src/core/game/PlayerImpl.ts
Labels: Bug Fix

#1073 bug: logout
  src/client/jwt.ts
Labels: Bug Fix

#1051 Duo partner SP always same: randomize players before team assignment
  src/core/game/TeamAssignment.ts
Labels: Bug Fix

#1078 Fix broken flag images
  src/client/data/countries.json
Labels: Bug Fix

#1079 Update PlayerImpl.ts
  src/core/game/PlayerImpl.ts
Labels: Balance Tweak, Bug Fix

#1080 Add filters tabs to EvensDisplay to let users filter events
  resources/lang/en.json
  src/client/Utils.ts
  src/client/graphics/layers/EventsDisplay.ts
  src/core/execution/AttackExecution.ts
  src/core/execution/MIRVExecution.ts
  src/core/execution/NukeExecution.ts
  src/core/execution/PlayerExecution.ts
  src/core/execution/SAMLauncherExecution.ts
  src/core/execution/SAMMissileExecution.ts
  src/core/execution/TradeShipExecution.ts
  src/core/execution/TransportShipExecution.ts
  src/core/game/Game.ts
  src/core/game/GameImpl.ts
  src/core/game/GameUpdates.ts
  src/core/game/PlayerImpl.ts
  src/core/game/UnitImpl.ts
  tests/MessageTypeClasses.test.ts
Labels: Feature - New

#1122 Adding unit info modal translation support.
  resources/lang/en.json
  src/client/graphics/layers/UnitInfoModal.ts
Labels: Translation - Revision

#1136 fix(client): use the right language-modal selector
  src/client/Main.ts
Labels: Bug Fix

#1148 * fix timer overflow
  src/client/graphics/layers/OptionsMenu.ts
  src/client/index.html
Labels: Bug Fix, UI/UX

#1151 * optimize leaderboard
  src/client/graphics/layers/Leaderboard.ts
Labels: Bug Fix, UI/UX

#1164 Rework leaderboard and team stats
  src/client/graphics/GameRenderer.ts
  src/client/graphics/icons/LeaderboardRegularIcon.ts
  src/client/graphics/icons/LeaderboardSolidIcon.ts
  src/client/graphics/icons/TeamRegularIcon.ts
  src/client/graphics/icons/TeamSolidIcon.ts
  src/client/graphics/layers/GameLeftSidebar.ts
  src/client/graphics/layers/Leaderboard.ts
  src/client/graphics/layers/TeamStats.ts
  src/client/index.html
Labels: Bug Fix, UI/UX

#1176 Fix Nations building more than allowed
  src/core/execution/FakeHumanExecution.ts
Labels: Bug Fix

#1216 Fix build menu on water tile
  src/client/graphics/layers/RadialMenuElements.ts
Labels: Bug Fix

#1215 Dependency removals and updates
  package-lock.json
  package.json
Labels: dependencies

#1161 upgrade to zod 4
  src/client/LocalServer.ts
  src/client/Transport.ts
  src/core/ApiSchemas.ts
  src/core/Schemas.ts
  src/core/StatsSchemas.ts
  src/core/WorkerSchemas.ts
  src/core/configuration/DefaultConfig.ts
  src/server/GameServer.ts
  src/server/jwt.ts
Labels: Backend Feature - New

#1220 Record MIRV warhead intercepted stats, perf improvements
  src/client/ClientGameRunner.ts
  src/client/graphics/layers/UnitInfoModal.ts
  src/core/configuration/DefaultConfig.ts
  src/core/execution/SAMLauncherExecution.ts
  src/core/execution/SAMMissileExecution.ts
  src/core/game/Game.ts
  src/core/game/GameView.ts
  src/core/game/PlayerImpl.ts
  src/core/game/Stats.ts
  src/core/game/StatsImpl.ts
  src/core/game/UnitGrid.ts
  tests/Stats.test.ts
Labels: Bug Fix, Performance Optimization

#1226 Simplfiy LangSelector
  src/client/LangSelector.ts
Labels: Feature - Revision, Performance Optimization

#1234 Logout Button Fix
  src/client/Main.ts
Labels: Bug Fix, UI/UX

#1235 Simplify ClientMessage handling
  src/client/LocalServer.ts
  src/client/Transport.ts
Labels: Bug Fix, Performance Optimization, UI/UX

#1255 Remove maxTokenAge
  src/server/jwt.ts
Labels: Backend Feature - Revision, Bug Fix

#786 Patterned territory
  resources/cosmetics/cosmetics.json
  resources/cosmetics/roles.txt
  resources/lang/en.json
  src/client/ClientGameRunner.ts
  src/client/Main.ts
  src/client/SinglePlayerModal.ts
  src/client/TerritoryPatternsModal.ts
  src/client/Transport.ts
  src/client/UserSettingModal.ts
  src/client/graphics/GameRenderer.ts
  src/client/graphics/layers/OptionsMenu.ts
  src/client/graphics/layers/TerritoryLayer.ts
  src/client/index.html
  src/core/ApiSchemas.ts
  src/core/CosmeticSchemas.ts
  src/core/Cosmetics.ts
  src/core/GameRunner.ts
  src/core/Schemas.ts
  src/core/execution/BotSpawner.ts
  src/core/game/Game.ts
  src/core/game/GameUpdates.ts
  src/core/game/GameView.ts
  src/core/game/PlayerImpl.ts
  src/core/game/UserSettings.ts
  src/server/Client.ts
  src/server/GameServer.ts
  src/server/Privilege.ts
  src/server/Worker.ts
  tests/Attack.test.ts
  tests/BotBehavior.test.ts
  tests/Disconnected.test.ts
  tests/MissileSilo.test.ts
  tests/PlayerInfo.test.ts
  tests/SAM.test.ts
  tests/Stats.test.ts
  tests/TeamAssignment.test.ts
  tests/TerritoryCapture.test.ts
  tests/UnitGrid.test.ts
  tests/Warship.test.ts
  tests/core/executions/NukeExecution.test.ts
  tests/util/Setup.ts
Labels: Feature - New, Premium, UI/UX

#892 Discounts can only be used one time
  src/core/configuration/DefaultConfig.ts
  src/core/execution/FakeHumanExecution.ts
  src/core/game/Game.ts
  src/core/game/PlayerImpl.ts
Labels: Balance Tweak

#1263 Refactor cosmetics.json
  resources/cosmetics/cosmetics.json
  resources/lang/en.json
  src/client/TerritoryPatternsModal.ts
  src/core/CosmeticSchemas.ts
  src/core/PatternDecoder.ts
  src/core/Schemas.ts
  src/core/game/GameView.ts
  src/core/game/UserSettings.ts
  src/server/Privilege.ts
  src/server/Worker.ts
Labels: Bug Fix, Feature - Revision, UI/UX

#1257 custom flag (1)
  resources/cosmetics/cosmetics.json
  resources/flags/custom/admin_contributors.svg
  resources/flags/custom/admin_evan.svg
  resources/flags/custom/admin_shield.svg
  resources/flags/custom/admin_shield_r.svg
  resources/flags/custom/beta_tester.svg
  resources/flags/custom/beta_tester_circle.svg
  resources/flags/custom/center_circle.svg
  resources/flags/custom/center_flower.svg
  resources/flags/custom/center_hline.svg
  resources/flags/custom/center_star.svg
  resources/flags/custom/center_vline.svg
  resources/flags/custom/diag_bl.svg
  resources/flags/custom/diag_br.svg
  resources/flags/custom/eu_star.svg
  resources/flags/custom/flower_tc.svg
  resources/flags/custom/flower_tl.svg
  resources/flags/custom/flower_tr.svg
  resources/flags/custom/frame.svg
  resources/flags/custom/full.svg
  resources/flags/custom/half_b.svg
  resources/flags/custom/half_l.svg
  resources/flags/custom/half_r.svg
  resources/flags/custom/half_t.svg
  resources/flags/custom/jp.svg
  resources/flags/custom/laurel_wreath.svg
  resources/flags/custom/mini_tr_bl.svg
  resources/flags/custom/mini_tr_br.svg
  resources/flags/custom/mini_tr_tl.svg
  resources/flags/custom/mini_tr_tr.svg
  resources/flags/custom/nato_emblem.svg
  resources/flags/custom/octagram.svg
  resources/flags/custom/octagram_2.svg
  resources/flags/custom/ofm_2025.svg
  resources/flags/custom/og.svg
  resources/flags/custom/og_plus.svg
  resources/flags/custom/rocket.svg
  resources/flags/custom/rocket_mini.svg
  resources/flags/custom/translator.svg
  resources/flags/custom/triangle_b.svg
  resources/flags/custom/triangle_bl.svg
  resources/flags/custom/triangle_br.svg
  resources/flags/custom/triangle_l.svg
  resources/flags/custom/triangle_r.svg
  resources/flags/custom/triangle_t.svg
  resources/flags/custom/triangle_tl.svg
  resources/flags/custom/triangle_tr.svg
  resources/flags/custom/tricolor_b.svg
  resources/flags/custom/tricolor_c.svg
  resources/flags/custom/tricolor_l.svg
  resources/flags/custom/tricolor_m.svg
  resources/flags/custom/tricolor_r.svg
  resources/flags/custom/tricolor_t.svg
  src/client/graphics/layers/NameLayer.ts
  src/client/graphics/layers/PlayerInfoOverlay.ts
  src/client/styles.css
  src/client/styles/core/flag-animation.css
  src/core/CosmeticSchemas.ts
  src/core/CustomFlag.ts
Labels: Premium

#1295 Graceful handling of ping before join
  src/server/Worker.ts
Labels: Bug Fix

#1298 Fix error-modal filling up the whole screen
  src/client/styles.css
Labels: Bug Fix, Feature - Revision, UI/UX
