Repository openfrontio/OpenFrontIO, pull requests merged in 2025-07, with the labels that each got.

#1311 Separate prod release environments
  .github/workflows/release.yml
Labels: GitHub Actions

#1312 Change news title to release notes
  .github/workflows/release.yml
  resources/lang/en.json
Labels: Translation - Revision

#1243 Better In Game UI
  resources/images/DarkModeIconWhite.svg
  resources/images/EmojiIconWhite.svg
  resources/images/ExitIconWhite.svg
  resources/images/ExplosionIconWhite.svg
  resources/images/FocusIconWhite.svg
  resources/images/InfoIconRegularWhite.svg
  resources/images/InfoIconSolidWhite.svg
  resources/images/LeaderboardIconRegularWhite.svg
  resources/images/LeaderboardIconSolidWhite.svg
  resources/images/MouseIconWhite.svg
  resources/images/NinjaIconWhite.svg
  resources/images/PauseIconWhite.svg
  resources/images/PlayIconWhite.svg
  resources/images/PopulationIconSolidWhite.svg
  resources/images/ReplayRegularIconWhite.svg
  resources/images/ReplaySolidIconWhite.svg
  resources/images/SamLauncherUnitWhite.png
  resources/images/TeamIconRegularWhite.svg
  resources/images/TeamIconSolidWhite.svg
  resources/images/TreeIconWhite.svg
  resources/images/TroopIconWhite.svg
  resources/images/WorkerIconBlack.svg
  resources/images/WorkerIconWhite.svg
  resources/lang/ar.json
  resources/lang/bg.json
  resources/lang/cs.json
  resources/lang/en.json
  resources/lang/eo.json
  resources/lang/es.json
  resources/lang/fr.json
  resources/lang/he.json
  resources/lang/it.json
  resources/lang/nl.json
  resources/lang/pl.json
  resources/lang/ru.json
  resources/lang/tp.json
  resources/lang/uk.json
  src/client/Main.ts
  src/client/graphics/GameRenderer.ts
  src/client/graphics/icons/LeaderboardRegularIcon.ts
  src/client/graphics/icons/LeaderboardSolidIcon.ts
  src/client/graphics/icons/TeamRegularIcon.ts
  src/client/graphics/icons/TeamSolidIcon.ts
  src/client/graphics/layers/ControlPanel.ts
  src/client/graphics/layers/GameLeftSidebar.ts
  src/client/graphics/layers/GameRightSidebar.ts
  src/client/graphics/layers/GameTopBar.ts
  src/client/graphics/layers/HeadsUpMessage.ts
  src/client/graphics/layers/PlayerInfoOverlay.ts
  src/client/graphics/layers/ReplayPanel.ts
  src/client/graphics/layers/SpawnTimer.ts
  src/client/graphics/layers/TopBar.ts
  src/client/index.html
  src/client/styles.css
  src/core/game/GameView.ts
Labels: UI/UX

#1316 w-320
  src/client/index.html
Labels: Bug Fix, UI/UX

#1305 Show structure levels
  resources/fonts/round_6x6_modified.png
  resources/fonts/round_6x6_modified.xml
  src/client/graphics/layers/StructureIconsLayer.ts
  src/global.d.ts
  webpack.config.js
Labels: Balance Tweak, Feature - New, UI/UX, Release Blocker

#1327 Additional patterns and subclass creation
  resources/cosmetics/cosmetics.json
  resources/lang/en.json
Labels: UI/UX

#1303 custom flag (2)
  resources/cosmetics/cosmetics.json
  src/client/TerritoryPatternsModal.ts
  src/core/CosmeticSchemas.ts
  src/core/PatternDecoder.ts
  src/core/Schemas.ts
  src/core/game/GameView.ts
  src/server/Privilege.ts
  src/server/Worker.ts
  tests/server/Privilege.customFlag.test.ts
Labels: Premium

#1333 Extend winner schema
  src/client/ClientGameRunner.ts
  src/client/graphics/layers/WinModal.ts
  src/core/Schemas.ts
  src/core/game/GameImpl.ts
  src/core/game/GameUpdates.ts
Labels: Release Blocker

#1336 mls 4.0
  resources/lang/bg.json
  resources/lang/da.json
  resources/lang/eo.json
  resources/lang/fi.json
  resources/lang/fr.json
  resources/lang/he.json
  resources/lang/ja.json
  resources/lang/ru.json
  resources/lang/sv_se.json
  resources/lang/uk.json
  resources/lang/zh_cn.json
  src/client/LangSelector.ts
Labels: Translation - New, Release Blocker

#1372 Add localization support for game events, settings, and UI text elements
  resources/lang/en.json
  src/client/graphics/layers/EventsDisplay.ts
  src/client/graphics/layers/GameRightSidebar.ts
  src/client/graphics/layers/OptionsMenu.ts
  src/client/graphics/layers/ReplayPanel.ts
  src/client/graphics/layers/SettingsModal.ts
Labels: Translation - Revision

#1371 Validate incoming parameters
  src/server/Master.ts
Labels: Bug Fix, Exploits and Security, Release Blocker

#1370 Add domain, subdomain to GameRecord
  src/client/ClientGameRunner.ts
  src/client/LocalServer.ts
  src/core/Schemas.ts
  src/core/Util.ts
  src/core/configuration/Config.ts
  src/core/configuration/DefaultConfig.ts
  src/server/Archive.ts
  src/server/GameServer.ts
  tests/util/TestServerConfig.ts
Labels: Release Blocker

#1375 bugfix: Crash during replay
  src/client/graphics/layers/ChatDisplay.ts
Labels: Release Blocker

#1383 Don't erase patterns on page load
  src/client/TerritoryPatternsModal.ts
  src/client/index.html
Labels: Bug Fix

#1384 fixed Custom Flags via Path Traversal
  src/core/Schemas.ts
Labels: Bug Fix, Exploits and Security

#1265 Fix: anonymized name isn't used in chat message
  src/client/graphics/layers/EventsDisplay.ts
  src/core/execution/QuickChatExecution.ts
Labels: Bug Fix

#1448 Tradeship performance
  src/core/execution/TradeShipExecution.ts
  tests/core/executions/TradeShipExecution.test.ts
Labels: Bug Fix, Performance Optimization

#1457 Fix: "Game speed" not "Replay speed" during Single player game
  src/client/graphics/layers/GameRightSidebar.ts
  src/client/graphics/layers/ReplayPanel.ts
Labels: Bug Fix

#1460 Fix: attack on ally even with greyed out button
  src/client/graphics/layers/RadialMenu.ts
Labels: Bug Fix

#1416 Fix language code mismatch during language switching
  resources/lang/pt_BR.json
  resources/lang/sv_SE.json
  resources/lang/zh_CN.json
  src/client/LangSelector.ts
Labels: Bug Fix, Translation - Revision

#1492 mls (v4.2)
  resources/lang/fi.json
  resources/lang/gl.json
  resources/lang/ru.json
  resources/lang/uk.json
  resources/lang/zh_CN.json
  src/client/LangSelector.ts
Labels: Translation - New, Translation - Revision

#1506 Fix .github/workflows/pr-description.yml to support current PR structure
  .github/workflows/pr-description.yml
Labels: Bug Fix, GitHub Actions

#1393 Make SpawnAd loading text translatable using translateText
  resources/lang/en.json
  src/client/graphics/layers/SpawnAd.ts
Labels: Translation - Revision

#1511 Fix language code mismatch during language switching (2)
  src/client/LangSelector.ts
Labels: Bug Fix

#1546 Zod v4 update
  package-lock.json
  package.json
  src/client/LocalServer.ts
  src/client/Transport.ts
  src/client/jwt.ts
  src/core/ApiSchemas.ts
  src/core/CosmeticSchemas.ts
  src/core/Schemas.ts
  src/core/StatsSchemas.ts
  src/core/WorkerSchemas.ts
  src/core/configuration/DefaultConfig.ts
  src/server/GameServer.ts
  src/server/Worker.ts
  src/server/jwt.ts
Labels: dependencies

#1532 Fix: display actual Alliance extension message instead of translation key
  src/client/graphics/layers/EventsDisplay.ts
  src/core/execution/alliance/AllianceExtensionExecution.ts
  src/core/game/Game.ts
  src/core/game/GameImpl.ts
  src/core/game/GameUpdates.ts
Labels: Bug Fix

#1535 Alliance Time to 5 minutes
  src/core/configuration/DefaultConfig.ts
Labels: Feature - Frontend

#1569 PR Template and Action Revsion
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-description.yml
Labels: Feature - DevOps

#1574 bugfix: when nuking nearby water, the attacker was not marked as a traitor on launch
  src/core/configuration/Config.ts
  src/core/configuration/DefaultConfig.ts
  src/core/execution/NukeExecution.ts
  tests/core/executions/NukeExecution.test.ts
Labels: Bug Fix

#1507 Add missing factory in player info panel
  resources/lang/en.json
  src/client/graphics/layers/PlayerInfoOverlay.ts
Labels: Bug Fix

#1320 Improve the alternate view by adding geopolitical colors for territories and hover-based highlighting
  src/client/InputHandler.ts
  src/client/graphics/GameRenderer.ts
  src/client/graphics/layers/NameLayer.ts
  src/client/graphics/layers/TerritoryLayer.ts
Labels: UI/UX

#1480 Change how canceled attacks are recorded
  src/core/execution/AttackExecution.ts
Labels: Bug Fix

#1442 Add the Pluto map
  resources/lang/en.json
  resources/maps/pluto/manifest.json
  resources/maps/pluto/map.bin
  resources/maps/pluto/mini_map.bin
  resources/maps/pluto/thumbnail.webp
  src/client/components/Maps.ts
  src/core/configuration/DefaultConfig.ts
  src/core/game/Game.ts
  src/server/MapPlaylist.ts
Labels: Feature - Map

#1578 mls (v4.3)
  resources/lang/bg.json
  resources/lang/da.json
  resources/lang/eo.json
  resources/lang/fi.json
  resources/lang/fr.json
  resources/lang/gl.json
  resources/lang/ja.json
  resources/lang/ko.json
  resources/lang/nl.json
  resources/lang/ru.json
  resources/lang/sl.json
  resources/lang/sv-SE.json
  resources/lang/uk.json
  resources/lang/zh-CN.json
  src/client/LangSelector.ts
Labels: Translation

#1566 Track gold obtained through eliminations in player stats
  src/core/execution/AttackExecution.ts
  tests/AttackStats.test.ts
Labels: Feature - Stats

#1581 Reduce docker image size with multi-stage build and dependency pruning
  Dockerfile
  package-lock.json
  package.json
  webpack.config.js
Labels: Feature - DevOps

#1582 Ensuring that MutableAlliance::extend is called in test case
  tests/AllianceExtensionExecution.test.ts
Labels: Feature - Test

#1577 Add Circassian nation
  resources/flags/Circassia.svg
  resources/maps/betweentwoseas/manifest.json
  resources/maps/blacksea/manifest.json
  src/client/data/countries.json
  src/core/execution/utils/BotNames.ts
Labels: Feature - Map

#1583 Change variable name from dKeyPressed to debugKeyPressed in LangSelector
  src/client/LangSelector.ts
Labels: Feature - Frontend, UI/UX

#1592 Improve UnitGrid performances by grouping units by type
  src/core/game/UnitGrid.ts
Labels: Feature - Performance

#1604 Allow additional modals to close when clicking the Escape key
  src/client/graphics/GameRenderer.ts
  src/client/graphics/layers/ChatModal.ts
  src/client/graphics/layers/EmojiTable.ts
  src/client/graphics/layers/PlayerPanel.ts
  src/client/graphics/layers/RadialMenu.ts
Labels: Feature - Frontend, UI/UX

#1616 Make Baikal More Common
  src/server/MapPlaylist.ts
Labels: Feature - Map

#1646 Enforce minimum test coverage
  .github/workflows/ci.yml
  jest.config.ts
  src/client/graphics/GameRenderer.ts
  src/client/graphics/layers/EmojiTable.ts
Labels: Feature - Test
