Repository openfrontio/OpenFrontIO, pull requests merged in 2025-08, with the labels that each got.

#1625 Shift scroll only increase
  src/client/InputHandler.ts
  src/client/graphics/layers/EventsDisplay.ts
Labels: Bug Fix, Feature - Frontend

#1669 Loosen coverage requirements slightly
  jest.config.ts
  src/client/graphics/layers/EmojiTable.ts
Labels: Feature - Test

#1621 Reduce Docker image size by refactoring map loading
  Dockerfile
  src/client/ClientGameRunner.ts
  src/client/HostLobbyModal.ts
  src/client/Main.ts
  src/client/PublicLobby.ts
  src/client/TerrainMapFileLoader.ts
  src/client/components/Maps.ts
  src/core/GameRunner.ts
  src/core/game/BinaryLoaderGameMapLoader.ts
  src/core/game/FetchGameMapLoader.ts
  src/core/game/GameMapLoader.ts
  src/core/game/TerrainMapLoader.ts
  src/core/worker/Worker.worker.ts
  tests/util/Setup.ts
  webpack.config.js
Labels: DevOps - CICD

#1436 Private Lobbies: Add kick player functionality
  resources/lang/en.json
  src/client/ClientGameRunner.ts
  src/client/HostLobbyModal.ts
  src/client/Main.ts
  src/client/Transport.ts
  src/client/styles.css
  src/core/Schemas.ts
  src/server/GameManager.ts
  src/server/GameServer.ts
  src/server/Worker.ts
Labels: Feature - Frontend, UI/UX

#1653 Further Darken Background Image for Dark Mode - Issue #1238
  src/client/index.html
Labels: Feature - Frontend, UI/UX

#1674 Add support for merge groups
  .github/workflows/ci.yml
Labels: DevOps - CICD

#1598 Add Split radial menu into separate attack and build buttons
  resources/lang/en.json
  src/client/graphics/layers/RadialMenuElements.ts
  tests/client/graphics/RadialMenuElements.test.ts
Labels: Feature - Frontend

#1647 contributor
  jest.config.ts
  resources/cosmetics/cosmetics.json
  resources/lang/en.json
Labels: Feature - Frontend

#1450 Remove gold from dead players
  src/core/execution/PlayerExecution.ts
Labels: Bug Fix

#1411 feature/prevent-from-accident-reloading
  src/client/index.html
Labels: Feature - Frontend

#1683 Remove unused processName util and twemoji dependency
  package-lock.json
  package.json
  src/core/Util.ts
  src/core/game/PlayerImpl.ts
Labels: dependencies

#1617 Allow main menu modals to be closed by clicking escape
  src/client/FlagInput.ts
  src/client/HelpModal.ts
  src/client/HostLobbyModal.ts
  src/client/JoinPrivateLobbyModal.ts
  src/client/LanguageModal.ts
  src/client/NewsModal.ts
  src/client/SinglePlayerModal.ts
  src/client/TerritoryPatternsModal.ts
  src/client/UserSettingModal.ts
  src/client/graphics/GameRenderer.ts
  src/client/graphics/layers/ChatModal.ts
  src/client/graphics/layers/PlayerPanel.ts
Labels: Feature - Frontend, UI/UX

#1688 Fix broken test
  tests/client/graphics/RadialMenuElements.test.ts
Labels: Bug Fix, Feature - Test

#1618 SAM smart targeting
  src/client/graphics/layers/UnitLayer.ts
  src/core/configuration/Config.ts
  src/core/configuration/DefaultConfig.ts
  src/core/execution/NukeExecution.ts
  src/core/execution/SAMLauncherExecution.ts
  src/core/execution/SAMMissileExecution.ts
  src/core/game/Game.ts
  src/core/game/UnitImpl.ts
  src/core/pathfinding/PathFinding.ts
  src/core/utilities/Line.ts
  tests/core/executions/SAMLauncherExecution.test.ts
Labels: Feature - Frontend, Feature - Simulation

#1665 Add random shell damage
  src/core/execution/ShellExecution.ts
  tests/ShellRandom.test.ts
Labels: Balance Tweak, Feature - Frontend

#1605 Fix Race conditions on alliances
  src/core/execution/AttackExecution.ts
  tests/Attack.test.ts
Labels: Bug Fix

#1689 Merge group
  .github/workflows/pr-description.yml
Labels: DevOps - CICD, Feature - Test

#1691 Merge group
  .github/workflows/ci.yml
  .github/workflows/pr-description.yml
Labels: DevOps - CICD, Feature - Test

#1655 Giant World Map Nations: fix spawn points, add new ones, change others
  resources/flags/Apartheid South Africa.svg
  resources/flags/Australian Aboriginal Flag.svg
  resources/flags/Burma2.svg
  resources/flags/Byelorussian SSR.svg
  resources/flags/Communist Romania.svg
  resources/flags/Georgian SSR.svg
  resources/flags/Imperial Ethiopia.svg
  resources/flags/Kazakh SSR.svg
  resources/flags/Mauritania.svg
  resources/flags/Newfoundland.svg
  resources/flags/North yemen.svg
  resources/flags/Nunavut.svg
  resources/flags/Pahlavi Iran.svg
  resources/flags/Rhodesia.svg
  resources/flags/Russian SSR.svg
  resources/flags/South Vietnam.svg
  resources/flags/Turkmen SSR.svg
  resources/flags/Ukrainian SSR.svg
  resources/flags/Yukon.svg
  resources/flags/south yemen.svg
  resources/maps/giantworldmap/manifest.json
Labels: Bug Fix, Feature - Map

#1693 Update the news modal
  resources/changelog.md
  resources/lang/en.json
  src/client/NewsModal.ts
Labels: Feature - Frontend, UI/UX

#1695 Fix invite link in Join Lobby
  src/client/JoinPrivateLobbyModal.ts
Labels: Bug Fix, Feature - Frontend, UI/UX

#1697 Rework trains to encourage alliances
  src/client/Utils.ts
  src/client/graphics/layers/FxLayer.ts
  src/core/configuration/DefaultConfig.ts
  src/core/execution/TrainExecution.ts
  src/core/game/GameUpdates.ts
  src/core/game/PlayerImpl.ts
  src/core/game/TrainStation.ts
  tests/core/game/TrainStation.test.ts
Labels: Balance Tweak, Feature - Simulation

#1606 Addition of FlagInputModal
  src/client/FlagInput.ts
  src/client/FlagInputModal.ts
  src/client/Main.ts
  src/client/components/baseComponents/Modal.ts
  src/client/index.html
Labels: Feature - Flags, UI/UX

#1666 Update viewport meta to contain user-scalable=no
  src/client/index.html
Labels: Feature - Frontend, UI/UX

#1643 Add comprehensive test for lang resource and flag existence
  tests/LangSvg.test.ts
Labels: Feature - Test

#1709 Fix: Automatically Close Flag Input Modal on Game Start
  src/client/Main.ts
Labels: Bug Fix

#1713 Disable strict mode
  tsconfig.json
Labels: Bug Fix, DevOps - CICD

#1435 Add a new Mars (Revised) map
  resources/lang/en.json
  resources/maps/marsrevised/manifest.json
  resources/maps/marsrevised/map.bin
  resources/maps/marsrevised/mini_map.bin
  resources/maps/marsrevised/thumbnail.webp
  src/client/components/Maps.ts
  src/core/configuration/DefaultConfig.ts
  src/core/game/Game.ts
  src/server/MapPlaylist.ts
Labels: Feature - Map

#1710 Fix: Modal background color does not cover entire content when alwaysMaximized is set
  src/client/components/baseComponents/Modal.ts
Labels: Bug Fix, Feature - Frontend

#1680 Switch to @swc/jest to speed up tests Fixes #1679
  .swcrc
  jest.config.ts
  package-lock.json
  package.json
Labels: Feature - Test

#1645 Add basic ICU message format support for translations
  package-lock.json
  package.json
  src/client/LangSelector.ts
  src/client/Utils.ts
Labels: Feature - Frontend, Translation

#1723 Add frontend-approver and backend-approver to CODEOWNERS file
  CODEOWNERS
Labels: DevOps - CICD

#1733 Cancel alliance requests if the recipient attacks
  src/client/graphics/layers/EventsDisplay.ts
  src/core/execution/AttackExecution.ts
  tests/Attack.test.ts
Labels: Balance Tweak, UI/UX, Feature - Simulation

#1737 Reintroduce commit metadata in the final image
  Dockerfile
Labels: Bug Fix, DevOps - CICD

#1761 Enable `@total-typescript/ts-reset`
  package-lock.json
  package.json
  src/client/ClientGameRunner.ts
  src/client/Cosmetics.ts
  src/client/InputHandler.ts
  src/client/JoinPrivateLobbyModal.ts
  src/client/LocalPersistantStats.ts
  src/client/MultiTabDetector.ts
  src/client/PublicLobby.ts
  src/client/UserSettingModal.ts
  src/core/ApiSchemas.ts
  src/core/CosmeticSchemas.ts
  src/core/ExpressSchemas.ts
  src/core/Schemas.ts
  src/core/WorkerSchemas.ts
  src/core/configuration/ConfigLoader.ts
  src/core/game/FetchGameMapLoader.ts
  src/core/game/TerrainMapLoader.ts
  src/core/game/UnitGrid.ts
  src/reset.d.ts
  src/server/Cloudflare.ts
  src/server/Master.ts
  src/server/Worker.ts
  tests/AutoUpgrade.test.ts
  tests/LangCode.test.ts
  tests/LangSvg.test.ts
  tests/testdata/maps/big_plains/manifest.json
  tests/testdata/maps/half_land_half_ocean/manifest.json
  tests/testdata/maps/ocean_and_land/manifest.json
  tests/testdata/maps/plains/manifest.json
  tests/util/Setup.ts
Labels: dependencies

#1762 Enable eslint warning for type assertions
  eslint.config.js
Labels: Feature - Test

#1753 mls (v4.4)
  resources/lang/bg.json
  resources/lang/da.json
  resources/lang/eo.json
  resources/lang/fi.json
  resources/lang/fr.json
  resources/lang/gl.json
  resources/lang/ja.json
  resources/lang/nl.json
  resources/lang/ru.json
  resources/lang/sk.json
  resources/lang/sl.json
  resources/lang/sv-SE.json
  resources/lang/uk.json
  resources/lang/zh-CN.json
  src/client/LangSelector.ts
Labels: Translation

#1530 Pause replay or SP game when opening Settings modal
  src/client/graphics/layers/GameRightSidebar.ts
  src/client/graphics/layers/SettingsModal.ts
Labels: Feature - Frontend, UI/UX

#1776 Remove CLA from the PR description
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-description.yml
Labels: DevOps - CICD

#1768 Make the player info overlay collapsible
  src/client/graphics/layers/PlayerInfoOverlay.ts
Labels: Feature - Frontend

#1752 Private lobby toggle donation
  resources/lang/en.json
  src/client/HostLobbyModal.ts
  src/client/SinglePlayerModal.ts
  src/client/graphics/layers/PlayerPanel.ts
  src/client/graphics/layers/RadialMenuElements.ts
  src/core/GameRunner.ts
  src/core/Schemas.ts
  src/core/configuration/Config.ts
  src/core/configuration/DefaultConfig.ts
  src/core/execution/DonateGoldExecution.ts
  src/core/execution/DonateTroopExecution.ts
  src/core/game/Game.ts
  src/core/game/PlayerImpl.ts
  src/server/GameManager.ts
  src/server/GameServer.ts
  src/server/MapPlaylist.ts
  tests/Donate.test.ts
  tests/client/graphics/RadialMenuElements.test.ts
  tests/util/Setup.ts
Labels: Feature - Frontend, Feature - Simulation

#1779 Enable eslint rule `@stylistic/ts/indent`
  .prettierignore
  eslint.config.js
  package-lock.json
  package.json
  src/client/HostLobbyModal.ts
  src/client/LangSelector.ts
  src/client/PublicLobby.ts
  src/client/UserSettingModal.ts
  src/client/graphics/layers/EventsDisplay.ts
  src/client/graphics/layers/PlayerPanel.ts
  src/client/graphics/layers/SettingsModal.ts
  src/client/graphics/layers/StructureIconsLayer.ts
  src/core/GameRunner.ts
  src/core/execution/FakeHumanExecution.ts
  src/core/execution/RailroadExecution.ts
  src/core/pathfinding/AStar.ts
  src/server/jwt.ts
  src/server/worker/websocket/handler/message/PreJoinHandler.ts
  webpack.config.js
Labels: DevOps - CICD

#1796 Enable various eslint rules
  eslint.config.js
Labels: DevOps - CICD

#1565 vote for winner
  eslint.config.js
  src/server/Client.ts
  src/server/GameServer.ts
  src/server/worker/websocket/handler/message/PostJoinHandler.ts
Labels: Feature - Backend, Exploits and Security, Release Blocker

#1810 eslint: Prefer `type.array()` over `z.array(type)`
  eslint-plugin-local/plugin.js
  eslint-plugin-local/rules/no-z-array.js
  eslint.config.js
  src/core/CosmeticSchemas.ts
Labels: DevOps - CICD

#1812 Fix flag preview not updating after selecting a new flag
  src/client/FlagInput.ts
Labels: Bug Fix

#1823 removed duplicate Papua New Guinea
  resources/maps/oceania/manifest.json
Labels: Bug Fix, Feature - Map

#1830 Enable the `@typescript-eslint/no-explicit-any` eslint rule
  eslint.config.js
  src/client/LangSelector.ts
  src/client/LanguageModal.ts
  src/client/Main.ts
  src/client/Utils.ts
  src/client/graphics/layers/EventsDisplay.ts
  src/client/graphics/layers/PlayerActionHandler.ts
  src/client/graphics/layers/RadialMenu.ts
  src/core/EventBus.ts
  src/core/Util.ts
  src/core/worker/Worker.worker.ts
  src/server/Cloudflare.ts
  src/server/GameServer.ts
  src/server/Master.ts
  src/server/Worker.ts
  src/server/worker/websocket/handler/message/PostJoinHandler.ts
Labels: DevOps - CICD

#1831 Enable the `@typescript-eslint/no-unsafe-argument` eslint rule
  eslint.config.js
  src/client/LangSelector.ts
  src/client/LanguageModal.ts
  src/client/Transport.ts
  src/client/graphics/layers/RadialMenu.ts
  src/core/game/PlayerImpl.ts
  tmp
Labels: DevOps - CICD

#1832 Enable the `@typescript-eslint/no-unsafe-assignment` eslint rule
  eslint-plugin-local/rules/no-z-array.js
  eslint.config.js
  src/client/LangSelector.ts
  src/client/UserSettingModal.ts
  src/client/Utils.ts
  src/client/components/baseComponents/setting/SettingSlider.ts
  src/client/graphics/NameBoxCalculator.ts
  src/core/execution/FakeHumanExecution.ts
  src/core/game/GameMap.ts
  src/server/Gatekeeper.ts
  src/server/Master.ts
  tmp
Labels: DevOps - CICD

#1833 Enable the `@typescript-eslint/no-unsafe-member-access` eslint rule
  eslint-plugin-local/rules/no-z-array.js
  eslint.config.js
  src/client/LangSelector.ts
  src/client/LanguageModal.ts
  src/client/Utils.ts
  src/client/graphics/layers/RadialMenu.ts
  src/server/Cloudflare.ts
  src/server/GameServer.ts
  src/server/Gatekeeper.ts
  src/server/Master.ts
  src/server/Worker.ts
Labels: DevOps - CICD

#1766 store & reference pattern by name
  src/client/ClientGameRunner.ts
  src/client/Cosmetics.ts
  src/client/Main.ts
  src/client/SinglePlayerModal.ts
  src/client/TerritoryPatternsModal.ts
  src/client/Transport.ts
  src/core/CosmeticSchemas.ts
  src/core/Schemas.ts
  src/core/game/GameView.ts
  src/core/game/UserSettings.ts
  src/server/Privilege.ts
  src/server/Worker.ts
Labels: Feature - Frontend, Premium, UI/UX

#1756 Display a dialog with join failure reason
  src/server/worker/websocket/handler/message/PreJoinHandler.ts
Labels: Feature - Frontend, UI/UX

#1842 Enable the Enable `max-len` and `max-lines` eslint rules
  eslint.config.js
  src/client/FlagInput.ts
  src/client/FlagInputModal.ts
  src/client/HostLobbyModal.ts
  src/client/JoinPrivateLobbyModal.ts
  src/client/LangSelector.ts
  src/client/LanguageModal.ts
  src/client/LocalServer.ts
  src/client/PublicLobby.ts
  src/client/SinglePlayerModal.ts
  src/client/TerritoryPatternsModal.ts
  src/client/UsernameInput.ts
  src/client/components/Difficulties.ts
  src/client/components/NewsButton.ts
  src/client/graphics/layers/ChatDisplay.ts
  src/client/graphics/layers/ControlPanel.ts
  src/client/graphics/layers/EmojiTable.ts
  src/client/graphics/layers/EventsDisplay.ts
  src/client/graphics/layers/GameLeftSidebar.ts
  src/client/graphics/layers/GameRightSidebar.ts
  src/client/graphics/layers/GutterAdModal.ts
  src/client/graphics/layers/Leaderboard.ts
  src/client/graphics/layers/MultiTabModal.ts
  src/client/graphics/layers/NameLayer.ts
  src/client/graphics/layers/OptionsMenu.ts
  src/client/graphics/layers/PlayerInfoOverlay.ts
  src/client/graphics/layers/RadialMenu.ts
  src/client/graphics/layers/SettingsModal.ts
  src/client/graphics/layers/SpawnAd.ts
  src/client/graphics/layers/UnitDisplay.ts
  src/core/Schemas.ts
  src/core/configuration/DefaultConfig.ts
  src/core/game/GameImpl.ts
  src/core/game/PlayerImpl.ts
  src/core/game/TerrainMapLoader.ts
  src/server/Worker.ts
  src/server/worker/websocket/handler/message/PreJoinHandler.ts
Labels: DevOps - CICD

#1843 fix: implement lazy loading for flag images and clean CSS
  src/client/FlagInputModal.ts
Labels: Bug Fix

#884 Add total units / buildings view to the teamstats component
  resources/lang/en.json
  src/client/graphics/layers/TeamStats.ts
Labels: Feature - Frontend

#1848 Enable the `no-undef` eslint rule
  eslint.config.js
  package-lock.json
  package.json
  src/client/ClientGameRunner.ts
  src/client/HostLobbyModal.ts
  src/client/InputHandler.ts
  src/client/JoinPrivateLobbyModal.ts
  src/client/LocalServer.ts
  src/client/graphics/TransformHandler.ts
  tests/MissileSilo.test.ts
  tests/PlayerImpl.test.ts
  tests/TeamAssignment.test.ts
  tests/UnitGrid.test.ts
  tests/core/executions/SAMLauncherExecution.test.ts
  tests/core/game/RailNetwork.test.ts
Labels: DevOps - CICD

#1921 Fix eslint failure
  src/client/TerritoryPatternsModal.ts
  src/core/execution/alliance/AllianceRequestExecution.ts
  tests/AllianceRequestExecution.test.ts
Labels: Bug Fix

#1900 Fix long-distance nuke interception
  src/core/execution/SAMLauncherExecution.ts
Labels: Bug Fix, Feature - Simulation

#1931 Nations build SAM launchers
  src/core/execution/FakeHumanExecution.ts
  src/core/execution/SAMLauncherExecution.ts
  src/core/execution/nation/structureSpawnTileValue.ts
Labels: Feature - AI, Feature - Simulation

#1935 Nations build defense posts
  src/core/execution/FakeHumanExecution.ts
  src/core/execution/nation/structureSpawnTileValue.ts
Labels: Balance Tweak, Feature - AI

#1911 Nations send emoji when declining assistance requests
  src/core/Util.ts
  src/core/execution/FakeHumanExecution.ts
  src/core/execution/utils/BotBehavior.ts
Labels: UI/UX, Feature - Simulation

#1938 more chat messages
  resources/QuickChat.json
  resources/lang/en.json
Labels: Feature - Frontend, UI/UX

#1947 Improve performance by reordering rendering layers
  src/client/graphics/GameRenderer.ts
Labels: Bug Fix, Feature - Frontend, Feature - Performance, UI/UX

#1860 bugfix: Nations rarely launch nukes
  src/core/execution/BotExecution.ts
  src/core/execution/FakeHumanExecution.ts
  src/core/execution/utils/BotBehavior.ts
Labels: Balance Tweak, Release Blocker, Feature - AI

#1956 Fix: Rework wheel and touch handling for pan and zoom
  src/client/InputHandler.ts
Labels: Feature - Frontend, UI/UX

#1959 Difficulty translation key
  resources/lang/en.json
  src/client/HostLobbyModal.ts
  src/client/SinglePlayerModal.ts
  src/client/components/Difficulties.ts
Labels: Translation

#1970 Simplify GameServer message creation
  src/server/GameServer.ts
Labels: Feature - Network, Feature - Performance
