Repository openfrontio/OpenFrontIO, pull requests merged in 2025-09, with the labels that each got.

#2000 Redesign Player info overlay
  resources/lang/en.json
  src/client/PublicLobby.ts
  src/client/Utils.ts
  src/client/graphics/layers/PlayerInfoOverlay.ts
  src/client/graphics/layers/PlayerPanel.ts
Labels: UI/UX

#2020 mls (v4.5)
  resources/lang/bg.json
  resources/lang/da.json
  resources/lang/eo.json
  resources/lang/fi.json
  resources/lang/fr.json
  resources/lang/gl.json
  resources/lang/hu.json
  resources/lang/ja.json
  resources/lang/pt-PT.json
  resources/lang/ru.json
  resources/lang/sk.json
  resources/lang/sl.json
  resources/lang/uk.json
  resources/lang/zh-CN.json
  src/client/LangSelector.ts
Labels: Translation

#2084 Add discord-user-header
  resources/lang/en.json
  src/client/components/baseComponents/stats/DiscordUserHeader.ts
Labels: UI/UX

#2099 Fix wrong og:image path
  src/client/index.html
Labels: Bug Fix

#2100 use pull_request_target for auto-assign
  .github/workflows/pr-author.yml
Labels: DevOps - CICD

#2108 Keep Lobby ID bar sticky at top of modal
  src/client/styles.css
Labels: UI/UX

#2120 mls (v4.6)
  resources/lang/bg.json
  resources/lang/eo.json
  resources/lang/fi.json
  resources/lang/fr.json
  resources/lang/hu.json
  resources/lang/ja.json
  resources/lang/mk.json
  resources/lang/pl.json
  resources/lang/ru.json
  resources/lang/sl.json
  resources/lang/tr.json
  resources/lang/uk.json
  resources/lang/zh-CN.json
  src/client/LangSelector.ts
Labels: Translation

#2113 Enable ESLint rule no-case-declarations
  eslint.config.js
  src/client/graphics/layers/UILayer.ts
  src/core/configuration/PastelTheme.ts
  src/core/configuration/PastelThemeDark.ts
Labels: DevOps - CICD
