Repository openfrontio/OpenFrontIO, pull requests merged in 2025-05, with the labels that each got.

#632 Update JWT schema
  src/client/ApiSchemas.ts
  src/client/Base64.ts
Labels: Backend Feature - Revision

#615 change team order to Red, Blue, Yellow, Green, Teal, Orange, Purple
  src/core/game/GameImpl.ts
  tests/TeamAssignment.test.ts
Labels: Feature - Revision, UI/UX

#629 Add API/DB request template
  .github/ISSUE_TEMPLATE/database_request.md
Labels: GitHub Actions

#648 display team count
  resources/lang/en.json
  resources/lang/ja.json
  src/client/PublicLobby.ts
Labels: UI/UX

#548 Added keybinding configuration.
  resources/lang/en.json
  resources/lang/es.json
  src/client/InputHandler.ts
  src/client/LangSelector.ts
  src/client/UserSettingModal.ts
  src/client/components/baseComponents/setting/SettingKeybind.ts
  src/client/styles/components/controls.css
  src/client/styles/components/setting.css
Labels: Feature - New, UI/UX

#654 fixed team count
  resources/lang/en.json
  resources/lang/ja.json
  src/client/PublicLobby.ts
Labels: Bug Fix, UI/UX

#667 Update deployment script to wait for deployment to come online
  .github/workflows/deploy.yml
Labels: GitHub Actions

#553 smoothed ship spawn rate function
  src/core/configuration/DefaultConfig.ts
Labels: Bug Fix

#661 Add anonymous name toggle to user settings
  resources/lang/en.json
  resources/lang/ja.json
  src/client/Main.ts
  src/client/RandomNameButton.ts
  src/client/UserSettingModal.ts
Labels: Bug Fix, Feature - Revision

#675 Update workflow files
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/eslint.yml
  .github/workflows/prettier.yml
Labels: GitHub Actions

#680 bugfix: Joining game fails
  src/core/Schemas.ts
  src/server/Worker.ts
Labels: Bug Fix

#674 Enforce UUID validation for persistent id
  src/core/Schemas.ts
Labels: Bug Fix

#685 Update github deployment status
  .github/workflows/deploy.yml
Labels: GitHub Actions

#686 MLS for Quick Chat
  resources/QuickChat.json
  resources/lang/en.json
  resources/lang/ja.json
  src/client/graphics/layers/ChatModal.ts
  src/client/graphics/layers/EventsDisplay.ts
  src/core/execution/QuickChatExecution.ts
  src/core/game/Game.ts
  src/core/game/GameImpl.ts
  src/core/game/GameUpdates.ts
Labels: Translation - New

#694 Fix leaderboard overlapping quick chat modal
  src/client/components/baseComponents/Modal.ts
  src/client/graphics/layers/Leaderboard.ts
Labels: Bug Fix

#734 Curved nuke trajectory
  src/client/graphics/layers/UnitLayer.ts
  src/core/execution/MIRVExecution.ts
  src/core/execution/NukeExecution.ts
  src/core/pathfinding/PathFinding.ts
  src/core/utilities/Line.ts
Labels: Backend Feature - New, UI/UX

#708 Cleanup deploy script
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/eslint.yml
  .github/workflows/prettier.yml
Labels: GitHub Actions

#752 mls-3
  resources/lang/ar.json
  resources/lang/bg.json
  resources/lang/eo.json
  resources/lang/fr.json
  resources/lang/it.json
  resources/lang/ja.json
  resources/lang/nl.json
  resources/lang/pl.json
  resources/lang/ru.json
  resources/lang/tp.json
  resources/lang/uk.json
  src/client/LangSelector.ts
Labels: Translation - New, Translation - Revision

#755 Mls4game
  resources/lang/en.json
  resources/lang/ja.json
  src/client/graphics/layers/BuildMenu.ts
  src/client/graphics/layers/ControlPanel.ts
  src/client/graphics/layers/Leaderboard.ts
  src/client/graphics/layers/PlayerInfoOverlay.ts
  src/client/graphics/layers/PlayerPanel.ts
  src/client/graphics/layers/TopBar.ts
  src/client/graphics/layers/WinModal.ts
Labels: Translation - Revision

#707 Feat : Auto remove embargoes that were automatically created
  src/core/configuration/Config.ts
  src/core/configuration/DefaultConfig.ts
  src/core/execution/AttackExecution.ts
  src/core/execution/EmbargoExecution.ts
  src/core/execution/FakeHumanExecution.ts
  src/core/execution/PlayerExecution.ts
  src/core/game/Game.ts
  src/core/game/GameImpl.ts
  src/core/game/PlayerImpl.ts
Labels: Feature - Revision

#706 Prevent multiple clients from using the same account
  src/client/SinglePlayerModal.ts
  src/server/GameServer.ts
Labels: Balance Tweak, Bug Fix

#795 bug: anon names
  src/core/game/GameView.ts
Labels: Bug Fix

#705 Boat retreat
  src/client/Transport.ts
  src/client/graphics/layers/EventsDisplay.ts
  src/core/Schemas.ts
  src/core/execution/BoatRetreatExecution.ts
  src/core/execution/ExecutionManager.ts
  src/core/execution/RetreatExecution.ts
  src/core/execution/TransportShipExecution.ts
  src/core/game/Game.ts
  src/core/game/GameUpdates.ts
  src/core/game/GameView.ts
  src/core/game/UnitImpl.ts
Labels: Backend Feature - New

#784 Record player stats during the game
  src/client/ClientGameRunner.ts
  src/client/LocalServer.ts
  src/client/graphics/layers/NameLayer.ts
  src/client/graphics/layers/PlayerPanel.ts
  src/core/ApiSchemas.ts
  src/core/ArchiveSchemas.ts
  src/core/Schemas.ts
  src/core/Util.ts
  src/core/execution/AttackExecution.ts
  src/core/execution/MIRVExecution.ts
  src/core/execution/NukeExecution.ts
  src/core/execution/PlayerExecution.ts
  src/core/execution/SAMMissileExecution.ts
  src/core/execution/ShellExecution.ts
  src/core/execution/TradeShipExecution.ts
  src/core/execution/TransportShipExecution.ts
  src/core/game/Game.ts
  src/core/game/GameImpl.ts
  src/core/game/GameUpdates.ts
  src/core/game/GameView.ts
  src/core/game/PlayerImpl.ts
  src/core/game/Stats.ts
  src/core/game/StatsImpl.ts
  src/core/game/UnitImpl.ts
  src/server/Archive.ts
  src/server/GameServer.ts
  src/server/Logger.ts
Labels: Feature - New, Release Blocker

#831 Transition flag from null to undefined
  src/core/Schemas.ts
  src/server/Client.ts
  src/server/GameServer.ts
Labels: Bug Fix, Release Blocker

#837 chat-fix
  src/core/execution/QuickChatExecution.ts
Labels: Bug Fix, Release Blocker

#605 feature: adds label for the team game mode with player team
  src/client/graphics/GameRenderer.ts
  src/client/graphics/layers/OptionsMenu.ts
  src/client/graphics/layers/PlayerTeamLabel.ts
  src/client/index.html
Labels: Feature - New, UI/UX

#435 New bot names
  src/core/execution/utils/BotNames.ts
Labels: Feature - Revision

#830 Add SAM interception FX
  resources/sprites/samExplosion.png
  src/client/graphics/AnimatedSpriteLoader.ts
  src/client/graphics/fx/Fx.ts
  src/client/graphics/fx/SAMExplosionFx.ts
  src/client/graphics/layers/FxLayer.ts
  src/core/execution/SAMLauncherExecution.ts
  src/core/execution/SAMMissileExecution.ts
  src/core/game/Game.ts
  src/core/game/GameUpdates.ts
  src/core/game/GameView.ts
  src/core/game/UnitImpl.ts
Labels: Feature - New

#847 Add ruins and desolation FX on nuke explosions
  resources/sprites/bigsmoke.png
  resources/sprites/minifire.png
  resources/sprites/smoke.png
  resources/sprites/smokeAndFire.png
  src/client/graphics/AnimatedSprite.ts
  src/client/graphics/AnimatedSpriteLoader.ts
  src/client/graphics/fx/Fx.ts
  src/client/graphics/fx/NukeFx.ts
  src/client/graphics/fx/SpriteFx.ts
  src/client/graphics/layers/FxLayer.ts
Labels: Feature - New

#818 SAM not working against MIRV warhead
  src/core/execution/NukeExecution.ts
  src/core/game/Game.ts
  src/core/game/UnitImpl.ts
  tests/SAM.test.ts
Labels: Bug Fix

#849 Display betrayal count (Continue #744)
  resources/lang/en.json
  src/client/graphics/layers/PlayerPanel.ts
  src/core/game/GameUpdates.ts
  src/core/game/PlayerImpl.ts
Labels: Bug Fix

#855 Better login handling
  resources/lang/en.json
  src/client/ClientGameRunner.ts
  src/client/LocalServer.ts
  src/client/Main.ts
  src/client/jwt.ts
Labels: Release Blocker

#740 Feat : focus attack average position and some movement camera fixes
  src/client/graphics/TransformHandler.ts
  src/client/graphics/layers/EventsDisplay.ts
  src/client/graphics/layers/Leaderboard.ts
  src/core/GameRunner.ts
  src/core/execution/AttackExecution.ts
  src/core/game/AttackImpl.ts
  src/core/game/Game.ts
  src/core/game/GameView.ts
  src/core/game/PlayerImpl.ts
  src/core/worker/Worker.worker.ts
  src/core/worker/WorkerClient.ts
  src/core/worker/WorkerMessages.ts
Labels: Feature - Revision

#869 mls4error
  resources/lang/en.json
  resources/lang/ja.json
  src/client/ClientGameRunner.ts
Labels: Translation - Revision

#877 Allow lowercase letters in clan name
  src/core/game/Game.ts
  tests/PlayerInfo.test.ts
Labels: Backend Feature - Revision

#848 Fix cache pathfinding
  src/core/execution/PortExecution.ts
  src/core/execution/TradeShipExecution.ts
  src/core/execution/TransportShipExecution.ts
  src/core/pathfinding/MiniAStar.ts
Labels: Release Blocker

#858 Add naval combat animations
  resources/sprites/miniExplosion.png
  resources/sprites/sinkingShip.png
  resources/sprites/unitExplosion.png
  src/client/graphics/AnimatedSpriteLoader.ts
  src/client/graphics/SpriteLoader.ts
  src/client/graphics/fx/Fx.ts
  src/client/graphics/fx/NukeFx.ts
  src/client/graphics/fx/SAMExplosionFx.ts
  src/client/graphics/fx/SpriteFx.ts
  src/client/graphics/fx/Timeline.ts
  src/client/graphics/fx/UnitExplosionFx.ts
  src/client/graphics/layers/FxLayer.ts
  src/core/execution/NukeExecution.ts
  src/core/execution/SAMLauncherExecution.ts
  src/core/execution/SAMMissileExecution.ts
  src/core/execution/ShellExecution.ts
  src/core/game/Game.ts
  src/core/game/GameUpdates.ts
  src/core/game/GameView.ts
  src/core/game/UnitImpl.ts
Labels: Feature - Revision

#889 Use array index access instead of .at
  src/core/execution/EmojiExecution.ts
Labels: Bug Fix

#867 Unit menu
  src/client/graphics/GameRenderer.ts
  src/client/graphics/layers/StructureLayer.ts
  src/client/graphics/layers/UnitInfoModal.ts
  src/client/index.html
  src/core/execution/MissileSiloExecution.ts
  src/core/execution/SAMLauncherExecution.ts
Labels: Feature - New, UI/UX

#929 Add test coverage script
  .gitignore
  jest.config.ts
  package.json
Labels: GitHub Actions

#930 Added two checkboxes to the default pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-description.yml
Labels: GitHub Actions

#965 Hide login button
  src/client/Main.ts
Labels: Bug Fix

#969 Fix discord user schema
  src/core/ApiSchemas.ts
Labels: Bug Fix

#984 Cap lobby sizes at 150
  src/core/configuration/DefaultConfig.ts
Labels: Balance Tweak

#983 Fix Translations showing as untranslated keys
  src/client/LangSelector.ts
Labels: Bug Fix
