Repository openfrontio/OpenFrontIO, pull requests merged in 2025-04, with the labels that each got.

#595 Fix Zimbabwe typo
  resources/maps/Africa.json
Labels: Bug Fix, Map - Revision

#606 Tile expansion
  src/core/execution/AttackExecution.ts
Labels: Balance Tweak

#427 Refactor Nations AI
  src/core/execution/BotExecution.ts
  src/core/execution/FakeHumanExecution.ts
  src/core/execution/utils/BotBehavior.ts
  src/core/game/PlayerImpl.ts
Labels: Backend Feature - Revision, Balance Tweak

#566 Use monospace font for private lobby code input
  src/client/styles.css
Labels: UI/UX

#590 Migrate subdomain deployments to their own GitHub environment
  .github/workflows/deploy.yml
  deploy.sh
Labels: GitHub Actions

#612 Shuffle playlist order
  src/server/MapPlaylist.ts
Labels: Bug Fix

#617 JWT decoding with jose
  package-lock.json
  package.json
  resources/lang/en.json
  src/client/ApiSchemas.ts
  src/client/Main.ts
  src/client/index.html
  src/client/jwt.ts
Labels: Feature - Revision, UI/UX
